name: CI
permissions: {}

on:
  schedule:
    # Run this job daily
    - cron: "0 8 * * *"
  # Allow starting this job manually
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true
  LIBC_CI: 1
  RUSTDOCFLAGS: -Dwarnings
  RUSTFLAGS: -Dwarnings
  RUST_BACKTRACE: full

jobs:
  test:
    name: Test
    strategy:
      matrix:
        include:
          # Set the list of targets you would like to test
          - target: x86_64-unknown-linux-gnu
    runs-on: ubuntu-26.04
    timeout-minutes: 25
    env:
      TARGET: ${{ matrix.target }}
    steps:
      # Check out this repository to `$GITHUB_WORKSPACE/downstream` for any needed files
      - uses: actions/checkout@v7
        with:
          path: downstream
      # Check out libc to `$GITHUB_WORKSPACE/rust-libc`
      - uses: actions/checkout@v7
        with:
          repository: rust-lang/libc
          # A job for `libc-0.2` may also be worth adding, though this updates
          # significantly less frequently.
          ref: main
          path: rust-libc
      - name: Setup Rust toolchain
        run: ./ci/install-rust.sh
      - uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.target }}

      - name: Apply patches
        run: git -C rust-libc am downstream/patches/*

      # Run tests using our patched dockerfile
      - name: Run in Docker
        run: cd rust-libc && ./ci/run-docker.sh ${{ matrix.target }}

      # Alternatively, if Docker is not needed, tests can be run in CI
      # - name: Run tests
      #   run: cd rust-libc && ./ci/run.sh ${{ matrix.target }}

      # Optional: Upload the result of
      # - name: Create CI artifacts
      #   id: create_artifacts
      #   if: always()
      #   run: cd rust-libc && python3 ci/create-artifacts.py
      # - uses: actions/upload-artifact@v7
      #   if: always() && steps.create_artifacts.outcome == 'success'
      #   with:
      #     name: ${{ env.ARCHIVE_NAME }}-${{ matrix.target }}${{ matrix.artifact-tag && format('-{0}', matrix.artifact-tag) }}
      #     path: ${{ env.ARCHIVE_PATH }}
      #     retention-days: 5
